# Build variants for pg-sui conda package

python:
  - 3.11

numpy:
  - 2.1

script_env:
  - PKG_VERSION
  - SETUPTOOLS_SCM_PRETEND_VERSION

# Keep channel ordering consistent during solve
channel_sources:
  - btmartin721,conda-forge,bioconda,pytorch,defaults
channel_targets:
  - btmartin721 main
