io:
  prefix: "pgsui"
  verbose: true
  debug: false
  seed: 42 # Random seed for reproducibility
  n_jobs: 1

model:
  latent_dim: 2
  dropout_rate: 0.2
  num_hidden_layers: 2
  activation: "relu" # relu | elu | selu | leaky_relu
  layer_schedule: "pyramid" # pyramid | constant | linear

train:
  batch_size: 64
  learning_rate: 0.001
  l1_penalty: 0.0
  early_stop_gen: 25
  min_epochs: 100
  max_epochs: 600
  validation_split: 0.2
  weights_max_ratio: 1.0
  weights_power: 1.0
  weights_inverse: false
  weights_normalize: false
  device: "cpu" # cpu | gpu | mps

tune:
  enabled: true
  metric: "f1" # f1 | accuracy | pr_macro
  n_trials: 100
  resume: false
  save_db: false
  fast: true
  patience: 50

plot:
  fmt: "pdf" # pdf | png | jpg | jpeg
  dpi: 300
  fontsize: 18
  despine: true
  show: false

vae:
  kl_beta: 1.0
